# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Start Jekyll
email: sackwort@gmail.com
description: >
  A guide to getting started with Jekyll
baseurl: "/startjekyll" # the subpath of your site, e.g. /blog
url: "http://sackwort.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  sackwort

# Build settings
include: ['_pages']
kramdown:
  input: GFM
